david/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^garrett/',include('garrett.urls',namespace = 'garrett')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

garrett/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signUp/$', views.signUp, name='signUp'),
    url(r'^pageSinger/$', views.pageSinger, name='pageSinger'),
    url(r'^pageSinger/(?P<singer_name>\w+)/$', views.singerSong, name='singerSong'),
    url(r'^song/(?P<song_id>[0-9]+)/$', views.singleSong, name='singleSong'),
    url(r'^allSong/$', views.allSong, name='allSong'),
    url(r'^404/$', views.page404, name='page404'),
    ]

garrett/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class users(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    passwrd = models.CharField(max_length=50, blank=False, null=False)


class authors(models.Model):
    singerID = models.CharField(max_length=10)
    name = models.CharField(max_length=100, blank=False, null=False)
    nation = models.CharField(max_length=100)
    birth = models.CharField(max_length=50)
    intro = models.TextField(max_length=500)
    picture = models.ImageField(upload_to='garrett', null=True)


class songs(models.Model):
    songID = models.IntegerField(blank=False, null=False)
    songName = models.CharField(max_length=120, blank=False, null=False)
    singerID = models.CharField(max_length=10, blank=False, null=False)
    songURL = models.CharField(max_length=100, blank=False, null=False)
    info = models.CharField(max_length=100, blank=False, null=False)


class commentPost(models.Model):
    songID = models.IntegerField(blank=False, null=False)
    account = models.CharField(max_length=20, blank=False, null=False)
    body = models.TextField()
    timestamp = models.DateTimeField()
    class Meta:
        ordering = ('-timestamp',)

garrett/forms.py
from django import forms
from django.contrib.auth.models import User

class loginForm(forms.Form):
    username=forms.CharField(required=True,label='username',
                             error_message={'required':'please input the username'},
                             widget=forms.TextInput(attrs={'placeholder':'username'}))
    password=forms.CharField(required=True,label='password',
                             error_message={'required':'please input the password'},
                             widget=forms.PasswordInput(attrs={'placeholder':'password'}))
    

garrett/views.py
from django.shortcuts import render

# Create your views here.
from datetime import datetime
from django import forms
from django.http import HttpResponseRedirect
from django.contrib import messages
from garrett.models import *

class userForm(forms.Form):
    account = forms.CharField(label = '',
                              widget = forms.TextInput(attrs={'placeholder':'Account',
                                                              'class':'form-control'}))
    password = forms.CharField(label = '',
                               widget = forms.PasswordInput(attrs={'placeholder':'Password',
                                                                   'class':'form-control'}))

class searchForm(forms.Form):
    srch = forms.CharField(label = '',
                             widget = forms.TextInput(attrs={'class':'form-control'}))


def index(request):
    if request.method == 'POST':
        uf1 = userForm(request.POST)
        if uf1.is_valid():
            account = uf1.cleaned_data['account']
            password = uf1.cleaned_data['password']
            index.user = users.objects.filter(name=account, passwrd=password)
            if index.user:
                return HttpResponseRedirect('/garrett/pageSinger/')
            else:
                messages.warning(request, 'informal error')
                return HttpResponseRedirect('/garrett/#signin')
    else:
        uf1 = userForm()
    return render(request, 'index.html',{'uf1':uf1})


def page404(request):
    if request.method == 'POST':
        sr = searchForm(request.POST)
        if sr.is_valid():
            want = sr.cleaned_data['srch']
            want = want.title()
            player = authors.objects.filter(name=want)
            singleSong = songs.objects.filter(songName=want)
            if player:
                return HttpResponseRedirect('/garrett/pageSinger/%s'\
                                            %player[0].singerID)
            elif singleSong:
                return HttpResponseRedirect('/garrett/song/%s'\
                                            %singleSong[0].songID)
            else:
                return HttpResponseRedirect('/garrett/404')
    else:
        sr = searchForm()
    contents = {'search': sr, 'user': index.user[0].name}
    return render(request, '404.html', contents)


def signUp(request):
    if request.method == 'POST':
        uf2 = userForm(request.POST)
        if uf2.is_valid():
            account = uf2.cleaned_data['account']
            password = uf2.cleaned_data['password']
            user = users.objects.filter(name=account)
            if user:
                messages.warning(request, 'used account')
            else:
                user = users()
                user.name = account
                user.passwrd = password
                user.save()
                messages.success(request, 'new account has been created!')
                return HttpResponseRedirect('/garrett/#signin')
    else:
        uf2 = userForm()
    return render(request, 'signUp.html', {'uf2':uf2})



def pageSinger(request):
    singers = authors.objects.all()
    if request.method == 'POST':
        sr = searchForm(request.POST)
        if sr.is_valid():
            want = sr.cleaned_data['srch']
            want = want.title()
            player = authors.objects.filter(name=want)
            singleSong = songs.objects.filter(songName=want)
            if player:
                return HttpResponseRedirect('/garrett/pageSinger/%s'\
                                            %player[0].singerID)
            elif singleSong:
                return HttpResponseRedirect('/garrett/song/%s'\
                                            %singleSong[0].songID)
            else:
                return HttpResponseRedirect('/garrett/404')
    else:
        sr = searchForm()
    contents = {'search': sr, 'singers': singers, 'user':index.user[0].name}
    return render(request, 'pageSinger.html', contents)
    
    

def singerSong(request, singer_name):
    author = authors.objects.get(singerID=singer_name)
    melodies = songs.objects.filter(singerID=singer_name)
    if request.method == 'POST':
        sr = searchForm(request.POST)
        if sr.is_valid():
            want = sr.cleaned_data['srch']
            want = want.title()
            player = authors.objects.filter(name=want)
            singleSong = songs.objects.filter(songName=want)
            if player:
                return HttpResponseRedirect('/garrett/pageSinger/%s'\
                                            %player[0].singerID)
            elif singleSong:
                return HttpResponseRedirect('/garrett/song/%s'\
                                            %singleSong[0].songID)
            else:
                return HttpResponseRedirect('/garrett/404')
    else:
        sr = searchForm()
    contents = {'author': author, 'songs': melodies, 'user': index.user[0].name,
                'search':sr}
    return render(request, 'authorSong.html', contents)


def singleSong(request, song_id):
    melody = songs.objects.get(pk=song_id)
    author = authors.objects.get(singerID=melody.singerID)
    comments = commentPost.objects.filter(songID=song_id)

    if request.method == 'POST':
        sr = searchForm(request.POST)
        if sr.is_valid():
            want = sr.cleaned_data['srch']
            want = want.title()
            player = authors.objects.filter(name=want)
            singleSong = songs.objects.filter(songName=want)
            if player:
                return HttpResponseRedirect('/garrett/pageSinger/%s'\
                                            %player[0].singerID)
            elif singleSong:
                return HttpResponseRedirect('/garrett/song/%s'\
                                            %singleSong[0].songID)
            else:
                return HttpResponseRedirect('/garrett/404')
        else:
            commentPost(songID=song_id, account=index.user[0].name,
                    body=request.POST.get('commentpost'),
                    timestamp=datetime.now()).save()
            return HttpResponseRedirect('/garrett/song/%s'%song_id)
    else:
        sr = searchForm()
        
    contents = {'user': index.user[0].name, 'melody': melody, 'author': author,
                'comments': comments, 'search': sr}
    return render(request, 'singleSong.html', contents)


def allSong(request):
    melodies = songs.objects.all()
    if request.method == 'POST':
        sr = searchForm(request.POST)
        if sr.is_valid():
            want = sr.cleaned_data['srch']
            want = want.title()
            player = authors.objects.filter(name=want)
            singleSong = songs.objects.filter(songName=want)
            if player:
                return HttpResponseRedirect('/garrett/pageSinger/%s'\
                                            %player[0].singerID)
            elif singleSong:
                return HttpResponseRedirect('/garrett/song/%s'\
                                            %singleSong[0].songID)
            else:
                return HttpResponseRedirect('/garrett/404')
    else:
        sr = searchForm()
    contents = {'melodies': melodies, 'user': index.user[0].name, 'search': sr}
    return render(request, 'allSong.html', contents)

garrett/templates/allSong.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>Classical Music Website</title>
	<style>
        #myCarousel{
          margin: 50px 0 0 0;
        }
    </style>

  <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                  <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-bar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a href="{% url 'garrett:pageSinger' %}" class="navbar-brand">Hello, {{ user }}</a>
                </div>
                <div class="collapse navbar-collapse" id="responsive-bar">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="">Song</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Choice<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'garrett:pageSinger' %}">Player</a></li>
                        <li><a href="{% url 'garrett:allSong' %}">Song</a></li>
                      </ul>
                    </li>
                    <li><a href="">log out</a></li>
                  </ul>
                  <form method="post" action="" class="navbar-form navbar-right">
                    <div class="form-group">
                      {% csrf_token %}
                      {{ search }}
                    </div>
                    <button type="submit" class="btn btn-default">search</button>
                  </form>
                </div>
            </div>
    </nav>

    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active" align="center" style="background:#0d100d">
          <img src="{% static 'img/david4.jpg' %}" alt="">
        </div>
        <div class="item" align="center" style="background:#a8a5a4">
          <img src="{% static 'img/celine2.jpg' %}" alt="">
        </div>
        <div class="item" align="center" style="background:#000000">
          <img src="{% static 'img/itzhak2.jpg' %}" alt="">
        </div>
      </div>
      <a href="#myCarousel" data-slide="prev" class="carousel-control left">&lsaquo;</a>
      <a href="#myCarousel"  data-slide="next" class="carousel-control right">&rsaquo;</a>
    </div>

    <div class="container" style="margin-top:20px">
      <ul class="list-unstyled">
        {% for melody in melodies %}
        <li><a href="{% url 'garrett:singleSong' melody.id %}"><h4 style="color:#333"><span class="glyphicon glyphicon-music"></span>&nbsp;{{ melody.songName }}</h4></a></li>
        {% endfor %}
      </ul>
    </div>

    
    <script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
    $(function(){
      $('#myCarousel').carousel({
        interval:4000
      })
    })
      </script>
</body>
</html>

garrett/templates/authorSong.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>Classical Music Website</title>
  <style>
    /*.div1{
      text-align: center;
      margin-top: 250px;
    }*/
  </style>
	<link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                  <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-bar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                    <a href="{% url 'garrett:pageSinger' %}" class="navbar-brand">Hello, {{ user }}</a>
                </div>
                <div class="collapse navbar-collapse" id="responsive-bar">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="#">{{ author.name }}</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Choice<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'garrett:pageSinger' %}">Player</a></li>
                        <li><a href="{% url 'garrett:allSong' %}">Song</a></li>
                      </ul>
                    </li>
                    <li><a href="/garrett">log out</a></li>
                  </ul>
                  <form method="post" action="" class="navbar-form navbar-right">
                    <div class="form-group">
                      {% csrf_token %}
                      {{ search }}
                    </div>
                    <button type="submit" class="btn btn-default">search</button>
                  </form>
                </div>
            </div>
    </nav>

    <div class="container" style="margin-top:100px">
      <table>
        <tr>
          <td width="50%">
            <img src="{{ author.picture.url }}" alt="">
          </td>
          <td padding="100px">
            <h4><strong>&nbsp;&nbsp;Author:</strong><small><b>{{ author.name }}</b></small></h4>
            <h4><strong>&nbsp;&nbsp;Nation:</strong><small><b>{{ author.nation }}</b></small></h4>
            <h4><strong>&nbsp;&nbsp;Birth:</strong><small><b>{{ author.birth }}</b></small></h4>
            </tr>
      </table>
        <br>
        <blockquote><p>{{ author.intro }}</p></blockquote>
    </div>

    <div class="container">
      <h1><span class="glyphicon glyphicon-headphones"></span>&nbsp;<ins>{{ author.name }}'s songs</ins></h1>
      <ul class="list-unstyled">
        {% for song in songs %}
        <li><a href="{% url 'garrett:singleSong' song.id %}"><h4 style="color:#333"><span class="glyphicon glyphicon-music"></span>&nbsp;{{ song.songName }}</h4></a></li>
        {% endfor %}
      </ul>
    </div>

    <script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

garrett/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Classical Music</title>

    <style>

        /*body{
            background: -webkit-linear-gradient(left, #555 0%, #333 100%);
            background: -o-linear-gradient(left, #555 0%, #333 100%);
            background: linear-gradient(to right, #555 0%, #333 100%);
          }*/

        body{
            margin-top:50px;
            background-position: 0% -25%;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-image: url("{% static 'img/5.jpg' %}");
        }

        .form-signin{
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .div-signin{
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
            background-color: #fff;
            background-color: rgba(0,0,0,0.1);
        }
        input{
            margin-bottom: 3px;
        }

  </style>

    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.1.min.js"></script>
   
  </head>

  

    <body data-spy="scroll" data-target=".navbar" data-offset="320">
        
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target="#myScroll">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'garrett:index' %}" class="navbar-brand">Welcome</a>
                </div>
                <div class="collapse navbar-collapse js-navbar-scrollspy" id="myScroll">
                    <ul class="nav navbar-nav">
                    <li><a href="#signin">Sign in</a></li>
                    <li><a href="{% url 'garrett:signUp' %}">Sign up</a></li>
                    </ul>
                </div>   
            </div>
        </nav>
 
        <div class="container">
            <br/><br/><br/><br/><br/><br/><br/><br/><br/>
            <h1>Classical Music WebSite</h1>
            <br/><br/><br/><br/><br/><br/><br/><br/>
            <div class='row'>
                <div class="col-md-2">
                    <button id='btn1' class="btn btn-lg btn-primary" type="button" name="signin">Click To Sign In</button>
                </div>
                <!-- <div class="col-md-2">
                    <button id='btn1' class="btn btn-lg btn-primary" type="button" name="signup">Click To Sign Up</button>
                </div> -->
            </div>
            <br/><br/><br/><br/><br/><br/><br/><br/>
        </div>

        <div id="signin" class="container-fluid" >
            <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
            <div class="div-signin">
                
            <form method='post' action="" class="form-signin">
            <!-- <form action="" class="form-horizontal"> -->
                <h2 class="form-signin-heading">Sign In</h2>
                <!-- <input type="text" class="form-control" placeholder="Account">
                <input type="password" class="form-control" placeholder="Password"> -->
                {% csrf_token %}
                {{ uf1 }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </form>
            </div>
                <br><br><br><br><br><br><br><br>
        </div>

        

    <script>
        $("button[name='signin']").click(function(){
            $('body,html').animate({scrollTop:$(window).height()},2000);
        });
        // $("button[name='signup']").click(function(){
        //     $('body,html').animate({scrollTop:$(window).height()*2+30},1500);
        // });
    </script>   

    <script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

    </body>
</html>

garrett/templates/pageSinger.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>Classical Music Website</title>
    <style>
        #myCarousel{
          margin: 50px 0 0 0;
        }
    </style>

  <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
  
</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                  <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-bar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                    <a href="{% url 'garrett:pageSinger' %}" class="navbar-brand">Hello, {{ user }}</a>
                </div>
                <div class="collapse navbar-collapse" id="responsive-bar">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="">Player</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Choice <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'garrett:pageSinger' %}">Player</a></li>
                        <li><a href="{% url 'garrett:allSong' %}">Song</a></li>
                      </ul>
                    </li>
                    <li><a href="{% url 'garrett:index' %}">log out</a></li>
                  </ul>
                  <form method="post" action="" class="navbar-form navbar-right">
                    <div class="form-group">
                      {% csrf_token %}
                      {{ search }}
                      <!-- <input type="text" class="form-control" name="search" value=''> -->
                    </div>
                    <button type="submit" class="btn btn-default">search</button>
                  </form>
                </div>
            </div>
    </nav>

    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active" align="center" style="background:#0d100d">
          <img src="{% static 'img/david4.jpg' %}" alt="">
        </div>
        <div class="item" align="center" style="background:#a8a5a4">
          <img src="{% static 'img/celine2.jpg' %}" alt="">
        </div>
        <div class="item" align="center" style="background:#000000">
          <img src="{% static 'img/itzhak2.jpg' %}" alt="">
        </div>
      </div>
      <a href="#myCarousel" data-slide="prev" class="carousel-control left">&lsaquo;</a>
      <a href="#myCarousel"  data-slide="next" class="carousel-control right">&rsaquo;</a>
    </div>

    <div class="container" style="margin:100px">
      <div class="row">
        {% for singer in singers %}
        <div class="col-xs-3 col-xs-offset-1">
          <img src={{ singer.picture.url }} alt="" class="img-circle" data-toggle="modal" data-target="#{{ singer.singerID }}">
        </div>
        {% endfor %}
      </div>
      <br>

      <div class="row">
        {% for singer in singers %}
        <div class="col-xs-3 col-xs-offset-1">
          <div class="container">
            <h4>
              <a style="color:#000;" href="{% url 'garrett:singerSong' singer.singerID %}">{{ singer.name }}</a>
            </h4>
          </div>
        </div>
        {% endfor %}
    </div>

   

      {% for singer in singers %}
      <div class="modal fade" id="{{ singer.singerID }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">{{ singer.name }}</h4>
            </div>
            <div class="modal-body">
              <table>
                <tr>
                  <td width="50%">
                    <img src="{{ singer.picture.url }}" alt="">
                  </td>
                  <td padding="100px">
                    <h4><strong>&nbsp;&nbsp;Author:</strong><small><b>{{ singer.name }}</b></small></h4>
                    <h4><strong>&nbsp;&nbsp;Nation:</strong><small><b>{{ singer.nation }}</b></small></h4>
                    <h4><strong>&nbsp;&nbsp;Birth:</strong><small><b>{{ singer.birth }}</b></small></h4>
                </tr>
              </table>
              <br>
              <blockquote><p>{{ singer.intro }}</p></blockquote>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}



    <!-- <img src="1.jpg" width="170" height="128" onMouseOut="this.src='1.jpg';" onMouseOver="this.src='2.jpg';"> -->
    <script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript">
    $(function(){
      $('#myCarousel').carousel({
        interval:4000
      })
    })

      $(function(){
        {% for singer in singers %}
      $("#{{ singer.singerID }}").modal({
        show:false
      });
        {% endfor %}
    })
      </script>
</body>
</html>

garrett/templates/signUp.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Classical Music</title>

	<style>	
		body{
            margin-top:50px;
            background-position: 0% -25%;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-image: url("{% static 'img/5.jpg' %}");
        }
        .form-signin{
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .div-signin{
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
            background-color: #fff;
            background-color: rgba(0,0,0,0.1);
        }
        input{
            margin-bottom: 3px;
        }
	</style>

	<link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target="#myScroll">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'garrett:index' %}" class="navbar-brand">Welcome</a>
                </div>
                <div class="collapse navbar-collapse js-navbar-scrollspy" id="myScroll">
                    <ul class="nav navbar-nav">
                    <li><a href="{% url 'garrett:index' %}#signin">Sign in</a></li>
                    <li class="active"><a href="{% url 'garrett:signUp' %}">Sign up</a></li>
                    </ul>
                </div>   
            </div>
    </nav>

    <div id="signup" class="container-fluid" >
            <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
            <div class="div-signin">
                
            <form method='post' action="" class="form-signin">
            <!-- <form action="" class="form-horizontal"> -->
                <h2 class="form-signin-heading">Sign Up</h2>
               <!--  <input type="text" class="form-control" placeholder="Account" />
                <input type="password" class="form-control" placeholder="Password" /> -->
                {% csrf_token %}
                {{ uf2 }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
                {% if messages %}
                <ul class="messages">
                	{% for message in messages %}
                	<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                		{{ message }}
                	</li>
                	{% endfor %}
                </ul>
                {% endif %}
            </form>
            </div>
                <br/><br/><br/><br/><br/><br/>
    </div>
    <script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

</body>
</html>